### ISSUE TITLE
P3E7 - parámetro en create_thread

### ISSUE THREAD

**Issue by yagopajarino** [honi/uba-so#1]
En [Práctica 3 / Ejercicio 7](https://github.com/honi/uba-so/blob/main/pr%C3%A1cticas/p3/ej07.md#pr%C3%A1ctica-3--ejercicio-7)

¿Cuando se crea el thread no debería pasarse `j` como parámetro?

```C
int N;
int i; // Primer proceso
semaphore s[N];

int main() {
    for (int j = 0; j < N; j++) {
        s[j] = sem(0);
        create_thread(j, run); 
        // create_thread(i, run);
    }
    s[i].signal();
}

void run(int i) {
    s[i].wait();
    printf("%d\n", i);
    s[(i+1) % N].signal();
}
```

**Comment by honi** [comment]
Si, tenes razón! Ahora lo arreglo, gracias por el reporte :)
